### ISSUE TITLE
Feature request: Set buffer options in gitcommit/NeogitCommitMessage filetype

### ISSUE THREAD

**Issue by catgoose** [NeogitOrg/neogit#1305]
**Is your feature request related to a problem? Please describe.**
I am unable to load `after/ftplugin/gitcommit` because https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/buffers/editor/init.lua#L174 sources `$VIMRUNTIME/ftplugin/gitcommit.vim` thus overwriting any buffer local options applied from the ftplugin or an autocmd.

To avoid the x/y problem what I really want to do is set `formatoptions` and `textwidth` for gitcommit filetype

**Describe the solution you'd like**
Several options:
1. NeogitCommitMessageCreated autocommand
2. Callback executed after gitcommit.vim is sourced
3. Create config option to set buffer/window opts for gitcommit filetype

**Describe alternatives you've considered**
I have tried several methods to set buffer local options to gitcommit/NeogitCommitMessage filetype: autocommands, after/ftplugin, etc

**Comment by CKolkey** [comment]
This is corrected.

**Comment by h67ma** [comment]
> This is corrected.

Corrected how? I still can't seem to set `formatoptions` (`NeogitCommitMessageCreated`/`BufEnter`/ftplugin). Could you provide an example how to do this (and preferably add it to docs)?

**Comment by CKolkey** [comment]
Sorry, here: 43fa47fb61773b0d90a78ebc2521ea8faaeebd86


You can use the gitcommit ftplugin
