### ISSUE TITLE
Discarding specific lines does not work

### ISSUE THREAD

**Issue by ptn** [NeogitOrg/neogit#1354]
### Description

In the status buffer, I cannot select specific lines in visual mode then press `x` to discard only those changes (as opposed to entire hunks or files). In previous versions, I would get a popup asking to confirm the discard, and then the discard would happen. That's not the case anymore.

This is hard to bisect because I encountered other bugs while doing so that made it impossible to trigger this behavior, but I can tell you that this was definitely working on d6b80dc9. On the commit immediately after that one (93773498), opening the status buffer prints debug information and I cannot use Tab to toggle file diffs.

### Neovim version

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202

### Operating system and version

macOS 13.4.1

### Steps to reproduce

1. Open status buffer
2. Use tab to open the fold of a modified file
3. Use visual mode to select specific lines in a hunk 
4. Press x

### Expected behavior

Popup asks for confirmation, then lines are discarded.

### Actual behavior

Neovim hangs, I actually need to press Ctrl-C to get it back. Doing that gives me this notification:

```
E5108: Error executing lua: ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: Keyboard interrupt
stack traceback:
	[C]: in function 'error'
	...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
	...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
	...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
	...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:118: in function 'cb'
	.../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:582: in function <.../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:581>
```

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```

**Comment by akrejczinger** [comment]
Pressing "u" to unstage selected lines also does not work:

```
git apply --reverse --cached:error: patch failed:
e2e/graphql_api/doc/source/requirements/pagination.rst:30    error:
e2e/graphql_api/doc/source/requirements/pagination.rst: patch does not apply
        An error occurred.
Press ENTER or type command to continue
```

**Comment by CKolkey** [comment]
Should be fixed here: https://github.com/NeogitOrg/neogit/pull/1411 - sorry about that

**Comment by thatanjan** [comment]
Hi @CKolkey , it is still not working for me. When I select a hunk, pressing `x` or `X` does nothing. I am using `2b74a777b963dfdeeabfabf84d5ba611666adab4` commit with the default configuration.

**Comment by CKolkey** [comment]
> Hi @CKolkey , it is still not working for me. When I select a hunk, pressing `x` or `X` does nothing. I am using `2b74a777b963dfdeeabfabf84d5ba611666adab4` commit with the default configuration.
> 
> 
> 
> I use NVIM v0.10.0

This issue is about discarding by _line_ - if you're having an issue with an entire hunk, open a new issue :)

**Comment by thatanjan** [comment]
Actually, I am facing the same problem that is mentioned in this issue.
When I select a specific line of changes and if I press `x` or `X`, I don't see any popup.
Demo:

https://github.com/user-attachments/assets/5c52b7ee-84df-4840-874a-70d597fcbe8b


Expected: 
![image](https://github.com/user-attachments/assets/1cdcd09c-6ce4-47dd-bf58-361fb764f8f6)
