### ISSUE TITLE
Neogit can't start up after PR #453 on Windows

### ISSUE THREAD

**Issue by Strongleong** [NeogitOrg/neogit#469]
### Description

After merging PR #453 Neogit does not work on Windows anymore. 
Here is error message with `Lazy.nvim`:
```
Failed to run `config` for neogit
...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:497: We couldn't mkdir: C:\Users\strongleong\AppData\Local\nvim-data/neogit/C:
# stacktrace:
  - plenary.nvim\lua\plenary\path.lua:497 _in_ **mkdir**
  - plenary.nvim\lua\plenary\path.lua:630 _in_ **touch**
  - neogit\lua\neogit\lib\state.lua:51 _in_ **read**
  - neogit\lua\neogit\lib\state.lua:33 _in_ **setup**
  - neogit\lua\neogit.lua:61 _in_ **setup**
  - neogit\lua\neogit.lua:76
  - ~\AppData\Local\nvim/lua/lazy-init.lua:16
  - ~\AppData\Local\nvim\init.lua:5
```

Error message with `minimal.lua`
```
packer.nvim: Error running config for neogit: ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:497: We couldn't mkdir: C:\Users\strongleong\AppData\Local\nvim-data/neogit/C:
```

P.S. Maybe add CI tests for Windows? 

### Neovim version

NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 10

### Steps to reproduce

1. `nvim -nu minimal.lua`

### Expected behavior

Neovim opens as usual, Neogit works properly 

### Actual behavior

Neovim opens with error, Neogit is not loaded

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by Strongleong** [comment]
Duplicate of #467

**Comment by UnderCooled** [comment]
> Just to clarify
> 
> Does this issue need more fixing, or why is and what needs to be replaced?
> 
> Windows is always the special of the bunch and is always having errors like this 😅. rmaggati/auto-session have also been struck by persistent file name paths.

Because Windows don't allow `:` in filename. For example:
`C:\Users\foo\bar -> C:%Users%foo%bar`
Neogit only replaces `\` to `%`, and Windows found a `:` in your filename, it cuts off `:` and the rest, filename becomes `C`, the drive letter.
So following what undofiles doing, you should replace `:` to `%`:
`C:\Users\foo\bar -> C%%Users%foo%bar`

**Comment by ten3roberts** [comment]
Right, though we would need to replace with something else as we need to convert back to `:` as well.

There are currently a rather large set of PRs merging into neogit now, but after that is done I'll take a shot at this, just to avoid conflicts.

**Comment by setibeings** [comment]
I have the same issue. On my system it's because `vim.loop.os_uname().sysname` returns something other than "Windows_NT". Specifically, it returns MINGW32_NT-10.0.

I've commented out the condition, and it works for me for now, but of course prevents me from using the same configuration files everywhere.

I feel like just using forward slashes as path separators everywhere "should" work like it does in many programming languages, even on windows. I'd be willing to open a PR if I figure out something I think would be acceptable.

**Comment by CKolkey** [comment]
I'd definitely appreciate any wondows related help. I don't have the OS to check against, so bug fixes for it are kinda hit-or-miss.

**Comment by wrightjjw** [comment]
> I'd definitely appreciate any wondows related help. I don't have the OS to check against, so bug fixes for it are kinda hit-or-miss.

I'm always willing to test out fixes, just tag me. Been pretty busy the past couple months but I'm hoping to be more active here now. I'll take a look at the current Windows issues later to see if I have any insight or fixes.

**Comment by setibeings** [comment]
So, I fixed this on my branch a few weeks ago, and while I didn't write tests, because there weren't adjacent tests and I ran out of time, I did test that things were working as expected on windows and linux. If anybody else wants to test out my changes, or write any unit tests, that would be welcome.

**Comment by ray-x** [comment]
Created a PR https://github.com/NeogitOrg/neogit/pull/917 tested with mingw and windows cmd

**Comment by wrightjjw** [comment]
This issue is not fixed after merging #877. I just tried doing a clean install, and I get the following error:
```
Failed to source `C:\Users\Joshua\AppData\Local\nvim\after/plugin/neogit.lua`  // this calls neogit.setup() in my config
vim/_editor.lua:341: C:\Users\Joshua\AppData\Local\nvim\init.lua..nvim_exec2() called at C:\Users\Joshua\AppData\Local\nvim\init.lua:0..C:\Users\Joshua\AppData\Local\nvim\after/plugin/neogit.lua: Vim(source):E5113: Error while calling lua chunk: ...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:643: Could not create file: C:\Users\Joshua\AppData\Local\nvim-data/neogit/%C%Users%Joshua
stack traceback:
^I[C]: in function 'error'
^I...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:643: in function 'touch'
^I...ata/Local/nvim-data/lazy/neogit/lua/neogit/lib/state.lua:51: in function 'read'
^I...ata/Local/nvim-data/lazy/neogit/lua/neogit/lib/state.lua:33: in function 'setup'
^I...oshua/AppData/Local/nvim-data/lazy/neogit/lua/neogit.lua:41: in function 'setup'
^IC:/Users/Joshua/AppData/Local/nvim/after/plugin/neogit.lua:1: in main chunk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua:341: in function 'cmd'
^I.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:481: in function <.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:480>
^I[C]: in function 'xpcall'
^I...ta/Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
^I.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:480: in function 'source'
^I.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:439: in function 'source_runtime'
^I.../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:140: in function 'startup'
^I...AppData\Local\nvim-data\lazy\lazy.nvim/lua/lazy/init.lua:110: in function 'setup'
^I...sers\Joshua\AppData\Local\nvim/lua/wrightjjw/plugins.lua:15: in main chunk
^I[C]: in function 'require'
^IC:\Users\Joshua\AppData\Local\nvim/lua/wrightjjw/init.lua:3: in main chunk
^I[C]: in function 'require'
^IC:\Users\Joshua\AppData\Local\nvim\init.lua:1: in main chunk
# stacktrace:
  - vim\_editor.lua:341 _in_ **cmd**
  - AppData\Local\nvim/lua/wrightjjw/plugins.lua:15
  - AppData\Local\nvim/lua/wrightjjw/init.lua:3
  - AppData\Local\nvim\init.lua:1
```

It is trying to create the file `C:\Users\Joshua\AppData\Local\nvim-data/neogit/%C%Users%Joshua` which is not a valid path.

**Comment by wrightjjw** [comment]
> It is trying to create the file `C:\Users\Joshua\AppData\Local\nvim-data/neogit/%C%Users%Joshua` which is not a valid path.

Manually creating ``C:\Users\Joshua\AppData\Local\nvim-data\neogit\` folder solves the problem. IIRC Shouldn't this be handled by plenary's `path:touch()`?

**Comment by CKolkey** [comment]
> > It is trying to create the file `C:\Users\Joshua\AppData\Local\nvim-data/neogit/%C%Users%Joshua` which is not a valid path.
> 
> 
> 
> Manually creating `C:\Users\Joshua\AppData\Local\nvim-data\neogit\` folder solves the problem. IIRC Shouldn't this be handled by plenary's `path:touch()`?

Yeah, it should per my understanding

**Comment by setibeings** [comment]
Perhaps making the parent directory as a separate step would help. I'd be happy to fix this, since it's apparently something I missed.

**Comment by setibeings** [comment]
I believe this issue is fixed now on the master branch. The most recent issue is because plenary does not recognize forward slashes as path separators on windows, even though forward slashes are interpreted as path separators by windows itself. The code now uses plenary to join the paths instead of concatenating strings, which _should_ mean that things still work as expected if a user convinces plenary to use forward slashes on windows.

**Comment by CKolkey** [comment]
Really appreciate your efforts here, @setibeings. I'll close this as the original issue is quite old, but if there arise more windows related things... >> new issue

**Comment by Strongleong** [comment]
@CKolkey there is still no CI/CD tests on windows

**Comment by setibeings** [comment]
> there is still no CI/CD tests on windows

@Strongleong This is the kind of thing that would have been easy enough to spot as a deficiency of a test if the mocked out paths were unix style only, and then easy to spot as a deficiency of the code when there's a colon in the actual results of the test. Unfortunately I didn't see any tests that cover these particular lines of code.

**Comment by CKolkey** [comment]
Ill be the first to admit the test coverage in this project isn't stellar. PR's are always welcome :)
