### ISSUE TITLE
Custom keys are not shown in the help popup, instead uses defaults

### ISSUE THREAD

**Issue by treatybreaker** [NeogitOrg/neogit#619]
**Is your feature request related to a problem? Please describe.**
Currently the help popup in the Status Buffer does not show the actually bound keys for each action, it's hardcoded.

**Describe the solution you'd like**
Use the actual mappings from the `config.mappings.status` to set the correct keys in the help popup.

**Additional context**
Follow up for #564

**Comment by treatybreaker** [comment]
This was resolved with the merge of #659

**Comment by karmicdude** [comment]
@treatybreaker or @CKolkey
now this issue is back on the rise
I set custom mappings for `mappings.status` table and it works, but help shows wrong information with default mappings

**Comment by miguno** [comment]
Same here. I modified the default keybinds (e.g., "u" should open the git pull popup instead of the default "unstage" behavior) and this works, i.e., "u" does open the pull popup. However, the hint does not reflect this configuration change: it still says "[u] unstage".

- Neovim 0.9.5
- "neogit": { "branch": "master", "commit": "760d6d74c328ce2a38b02677bf5161999b992da2" }
